# Generated by Django 4.1.3 on 2022-11-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='posted_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
