# Generated by Django 4.0.4 on 2022-06-27 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_alter_user_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=300, null=True)),
                ('startingBid', models.FloatField()),
                ('currentBid', models.FloatField()),
                ('pic_url', models.CharField(max_length=300)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_cat', to='auctions.category')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('watchers', models.ManyToManyField(blank=True, related_name='watched_ppl', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
