# Generated by Django 4.0.4 on 2022-07-02 02:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_remove_category_id_alter_category_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='buyer',
        ),
        migrations.AddField(
            model_name='listing',
            name='buyer',
            field=models.ManyToManyField(blank=True, related_name='buyers', to=settings.AUTH_USER_MODEL),
        ),
    ]
